/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/router/__root'
import { Route as IndexRouteImport } from './app/router/index'
import { Route as dashboardDashboardRouteImport } from './app/router/(dashboard)/_dashboard'
import { Route as authAuthRouteImport } from './app/router/(auth)/_auth'
import { Route as authAuthLoginRouteImport } from './app/router/(auth)/_auth.login'
import { Route as dashboardDashboardTransactionsIndexRouteImport } from './app/router/(dashboard)/_dashboard.transactions/index'
import { Route as dashboardDashboardDashboardIndexRouteImport } from './app/router/(dashboard)/_dashboard.dashboard/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardRoute = dashboardDashboardRouteImport.update({
  id: '/(dashboard)/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthRoute,
} as any)
const dashboardDashboardTransactionsIndexRoute =
  dashboardDashboardTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardDashboardIndexRoute =
  dashboardDashboardDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authAuthLoginRoute
  '/dashboard': typeof dashboardDashboardDashboardIndexRoute
  '/transactions': typeof dashboardDashboardTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authAuthLoginRoute
  '/dashboard': typeof dashboardDashboardDashboardIndexRoute
  '/transactions': typeof dashboardDashboardTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(dashboard)/_dashboard': typeof dashboardDashboardRouteWithChildren
  '/(auth)/_auth/login': typeof authAuthLoginRoute
  '/(dashboard)/_dashboard/dashboard/': typeof dashboardDashboardDashboardIndexRoute
  '/(dashboard)/_dashboard/transactions/': typeof dashboardDashboardTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/dashboard' | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard' | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/(auth)/_auth'
    | '/(dashboard)/_dashboard'
    | '/(auth)/_auth/login'
    | '/(dashboard)/_dashboard/dashboard/'
    | '/(dashboard)/_dashboard/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authAuthRoute: typeof authAuthRouteWithChildren
  dashboardDashboardRoute: typeof dashboardDashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_dashboard': {
      id: '/(dashboard)/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth/login': {
      id: '/(auth)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(dashboard)/_dashboard/transactions/': {
      id: '/(dashboard)/_dashboard/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof dashboardDashboardTransactionsIndexRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/_dashboard/dashboard/': {
      id: '/(dashboard)/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardDashboardIndexRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
  }
}

interface authAuthRouteChildren {
  authAuthLoginRoute: typeof authAuthLoginRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthLoginRoute: authAuthLoginRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface dashboardDashboardRouteChildren {
  dashboardDashboardDashboardIndexRoute: typeof dashboardDashboardDashboardIndexRoute
  dashboardDashboardTransactionsIndexRoute: typeof dashboardDashboardTransactionsIndexRoute
}

const dashboardDashboardRouteChildren: dashboardDashboardRouteChildren = {
  dashboardDashboardDashboardIndexRoute: dashboardDashboardDashboardIndexRoute,
  dashboardDashboardTransactionsIndexRoute:
    dashboardDashboardTransactionsIndexRoute,
}

const dashboardDashboardRouteWithChildren =
  dashboardDashboardRoute._addFileChildren(dashboardDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authAuthRoute: authAuthRouteWithChildren,
  dashboardDashboardRoute: dashboardDashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
