/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/router/__root'
import { Route as IndexRouteImport } from './app/router/index'
import { Route as dashboardDashboardRouteImport } from './app/router/(dashboard)/_dashboard'
import { Route as authAuthRouteImport } from './app/router/(auth)/_auth'
import { Route as dashboardDashboardTransactionsRouteImport } from './app/router/(dashboard)/_dashboard.transactions'
import { Route as dashboardDashboardDashboardRouteImport } from './app/router/(dashboard)/_dashboard.dashboard'
import { Route as dashboardDashboardCategoriesRouteImport } from './app/router/(dashboard)/_dashboard.categories'
import { Route as dashboardDashboardBudgetsRouteImport } from './app/router/(dashboard)/_dashboard.budgets'
import { Route as dashboardDashboardAssistantRouteImport } from './app/router/(dashboard)/_dashboard.assistant'
import { Route as dashboardDashboardAnalyticsRouteImport } from './app/router/(dashboard)/_dashboard.analytics'
import { Route as authAuthRegisterRouteImport } from './app/router/(auth)/_auth.register'
import { Route as authAuthLoginRouteImport } from './app/router/(auth)/_auth.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardRoute = dashboardDashboardRouteImport.update({
  id: '/(dashboard)/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardTransactionsRoute =
  dashboardDashboardTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardDashboardRoute =
  dashboardDashboardDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardCategoriesRoute =
  dashboardDashboardCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardBudgetsRoute =
  dashboardDashboardBudgetsRouteImport.update({
    id: '/budgets',
    path: '/budgets',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardAssistantRoute =
  dashboardDashboardAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardAnalyticsRoute =
  dashboardDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const authAuthRegisterRoute = authAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authAuthLoginRoute
  '/register': typeof authAuthRegisterRoute
  '/analytics': typeof dashboardDashboardAnalyticsRoute
  '/assistant': typeof dashboardDashboardAssistantRoute
  '/budgets': typeof dashboardDashboardBudgetsRoute
  '/categories': typeof dashboardDashboardCategoriesRoute
  '/dashboard': typeof dashboardDashboardDashboardRoute
  '/transactions': typeof dashboardDashboardTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authAuthLoginRoute
  '/register': typeof authAuthRegisterRoute
  '/analytics': typeof dashboardDashboardAnalyticsRoute
  '/assistant': typeof dashboardDashboardAssistantRoute
  '/budgets': typeof dashboardDashboardBudgetsRoute
  '/categories': typeof dashboardDashboardCategoriesRoute
  '/dashboard': typeof dashboardDashboardDashboardRoute
  '/transactions': typeof dashboardDashboardTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(dashboard)/_dashboard': typeof dashboardDashboardRouteWithChildren
  '/(auth)/_auth/login': typeof authAuthLoginRoute
  '/(auth)/_auth/register': typeof authAuthRegisterRoute
  '/(dashboard)/_dashboard/analytics': typeof dashboardDashboardAnalyticsRoute
  '/(dashboard)/_dashboard/assistant': typeof dashboardDashboardAssistantRoute
  '/(dashboard)/_dashboard/budgets': typeof dashboardDashboardBudgetsRoute
  '/(dashboard)/_dashboard/categories': typeof dashboardDashboardCategoriesRoute
  '/(dashboard)/_dashboard/dashboard': typeof dashboardDashboardDashboardRoute
  '/(dashboard)/_dashboard/transactions': typeof dashboardDashboardTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/analytics'
    | '/assistant'
    | '/budgets'
    | '/categories'
    | '/dashboard'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/analytics'
    | '/assistant'
    | '/budgets'
    | '/categories'
    | '/dashboard'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/(auth)/_auth'
    | '/(dashboard)/_dashboard'
    | '/(auth)/_auth/login'
    | '/(auth)/_auth/register'
    | '/(dashboard)/_dashboard/analytics'
    | '/(dashboard)/_dashboard/assistant'
    | '/(dashboard)/_dashboard/budgets'
    | '/(dashboard)/_dashboard/categories'
    | '/(dashboard)/_dashboard/dashboard'
    | '/(dashboard)/_dashboard/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authAuthRoute: typeof authAuthRouteWithChildren
  dashboardDashboardRoute: typeof dashboardDashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_dashboard': {
      id: '/(dashboard)/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_dashboard/transactions': {
      id: '/(dashboard)/_dashboard/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof dashboardDashboardTransactionsRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/_dashboard/dashboard': {
      id: '/(dashboard)/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardDashboardRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/_dashboard/categories': {
      id: '/(dashboard)/_dashboard/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof dashboardDashboardCategoriesRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/_dashboard/budgets': {
      id: '/(dashboard)/_dashboard/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof dashboardDashboardBudgetsRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/_dashboard/assistant': {
      id: '/(dashboard)/_dashboard/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof dashboardDashboardAssistantRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/_dashboard/analytics': {
      id: '/(dashboard)/_dashboard/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof dashboardDashboardAnalyticsRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(auth)/_auth/register': {
      id: '/(auth)/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authAuthRegisterRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/login': {
      id: '/(auth)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
  }
}

interface authAuthRouteChildren {
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthRegisterRoute: typeof authAuthRegisterRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthRegisterRoute: authAuthRegisterRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface dashboardDashboardRouteChildren {
  dashboardDashboardAnalyticsRoute: typeof dashboardDashboardAnalyticsRoute
  dashboardDashboardAssistantRoute: typeof dashboardDashboardAssistantRoute
  dashboardDashboardBudgetsRoute: typeof dashboardDashboardBudgetsRoute
  dashboardDashboardCategoriesRoute: typeof dashboardDashboardCategoriesRoute
  dashboardDashboardDashboardRoute: typeof dashboardDashboardDashboardRoute
  dashboardDashboardTransactionsRoute: typeof dashboardDashboardTransactionsRoute
}

const dashboardDashboardRouteChildren: dashboardDashboardRouteChildren = {
  dashboardDashboardAnalyticsRoute: dashboardDashboardAnalyticsRoute,
  dashboardDashboardAssistantRoute: dashboardDashboardAssistantRoute,
  dashboardDashboardBudgetsRoute: dashboardDashboardBudgetsRoute,
  dashboardDashboardCategoriesRoute: dashboardDashboardCategoriesRoute,
  dashboardDashboardDashboardRoute: dashboardDashboardDashboardRoute,
  dashboardDashboardTransactionsRoute: dashboardDashboardTransactionsRoute,
}

const dashboardDashboardRouteWithChildren =
  dashboardDashboardRoute._addFileChildren(dashboardDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authAuthRoute: authAuthRouteWithChildren,
  dashboardDashboardRoute: dashboardDashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
