/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/router/__root'
import { Route as IndexRouteImport } from './app/router/index'
import { Route as dashboardDashboardRouteImport } from './app/router/(dashboard)/_dashboard'
import { Route as authAuthRouteImport } from './app/router/(auth)/_auth'
import { Route as authAuthLoginRouteImport } from './app/router/(auth)/_auth.login'
import { Route as dashboardDashboardUserIndexRouteImport } from './app/router/(dashboard)/_dashboard.user/index'
import { Route as dashboardDashboardUserUserIdRouteImport } from './app/router/(dashboard)/_dashboard.user/$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardRoute = dashboardDashboardRouteImport.update({
  id: '/(dashboard)/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthRoute,
} as any)
const dashboardDashboardUserIndexRoute =
  dashboardDashboardUserIndexRouteImport.update({
    id: '/user/',
    path: '/user/',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardUserUserIdRoute =
  dashboardDashboardUserUserIdRouteImport.update({
    id: '/user/$userId',
    path: '/user/$userId',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authAuthLoginRoute
  '/user/$userId': typeof dashboardDashboardUserUserIdRoute
  '/user': typeof dashboardDashboardUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authAuthLoginRoute
  '/user/$userId': typeof dashboardDashboardUserUserIdRoute
  '/user': typeof dashboardDashboardUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(dashboard)/_dashboard': typeof dashboardDashboardRouteWithChildren
  '/(auth)/_auth/login': typeof authAuthLoginRoute
  '/(dashboard)/_dashboard/user/$userId': typeof dashboardDashboardUserUserIdRoute
  '/(dashboard)/_dashboard/user/': typeof dashboardDashboardUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/user/$userId' | '/user'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/user/$userId' | '/user'
  id:
    | '__root__'
    | '/'
    | '/(auth)/_auth'
    | '/(dashboard)/_dashboard'
    | '/(auth)/_auth/login'
    | '/(dashboard)/_dashboard/user/$userId'
    | '/(dashboard)/_dashboard/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authAuthRoute: typeof authAuthRouteWithChildren
  dashboardDashboardRoute: typeof dashboardDashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_dashboard': {
      id: '/(dashboard)/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth/login': {
      id: '/(auth)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(dashboard)/_dashboard/user/': {
      id: '/(dashboard)/_dashboard/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof dashboardDashboardUserIndexRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/_dashboard/user/$userId': {
      id: '/(dashboard)/_dashboard/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof dashboardDashboardUserUserIdRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
  }
}

interface authAuthRouteChildren {
  authAuthLoginRoute: typeof authAuthLoginRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthLoginRoute: authAuthLoginRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface dashboardDashboardRouteChildren {
  dashboardDashboardUserUserIdRoute: typeof dashboardDashboardUserUserIdRoute
  dashboardDashboardUserIndexRoute: typeof dashboardDashboardUserIndexRoute
}

const dashboardDashboardRouteChildren: dashboardDashboardRouteChildren = {
  dashboardDashboardUserUserIdRoute: dashboardDashboardUserUserIdRoute,
  dashboardDashboardUserIndexRoute: dashboardDashboardUserIndexRoute,
}

const dashboardDashboardRouteWithChildren =
  dashboardDashboardRoute._addFileChildren(dashboardDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authAuthRoute: authAuthRouteWithChildren,
  dashboardDashboardRoute: dashboardDashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
